
    <table class="admin__control-table" id="searchautocomplete-indices">
        <?php if (!empty($block->getData('options')) || empty($block->getData('field_id'))): ?>
            <?php foreach ($block->getOptionData($block->getData('options')) as $index): ?>
            <tr>
                <td class="col-order" data-role="draggable-handle">
                    <input type="hidden" data-role="order"
                           name="<?= $escaper->escapeHtmlAttr($block->getNamePrefix($index)) ?>[order]"
                           value="<?= $escaper->escapeHtmlAttr((string)$index['order']) ?>">
                </td>
                <td class="col-title"><?= $escaper->escapeHtml((string)$index['title']) ?></td>
                 <td class="col-limit">
                   <select
                       name="<?= $escaper->escapeHtmlAttr($block->getNamePrefix($index)) ?>[limit]"
                       class="admin__control-select">
                        <?php
                            $selectedLimit = $index['limit'] ?? ''; // Get selected value
                            $options = $block->getDropdownOptions(); // Fetch options from block
                        ?>
                        <?php foreach ($options as $value => $label): ?>
                            <option
                                value="<?= $escaper->escapeHtmlAttr((string)$value) ?>"
                                <?= $selectedLimit == $value ? 'selected' : '' ?>>
                                <?= $escaper->escapeHtml((string)$label) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                    <input
                        type="hidden"
                        name="<?= $escaper->escapeHtmlAttr($block->getNamePrefix($index)) ?>[type]"
                        value="<?= $escaper->escapeHtmlAttr((string)($index['type'] ?? '')) ?>"/>
                    <input
                        type="hidden"
                        name="<?= $escaper->escapeHtmlAttr($block->getNamePrefix($index)) ?>[identifier]"
                        value="<?= $escaper->escapeHtmlAttr((string)($index['identifier'] ?? '')) ?>"/>
                    <input
                        type="hidden"
                        name="<?= $escaper->escapeHtmlAttr($block->getNamePrefix($index)) ?>[title]"
                        value="<?= $escaper->escapeHtmlAttr((string)($index['title'] ?? '')) ?>"/>

                </td>
            </tr>
        <?php endforeach ?>
        <?php else: ?>
        <td style="color: red;">Template variables not available</td>
        <?php endif ?>
    </table>
<script>
    require([
        'jquery',
        'collapsable'
    ], function ($) {
        var list = $('#searchautocomplete-indices');
        list.sortable({
            axis:      'y',
            handle:    '[data-role=draggable-handle]',
            items:     'tr',
            update:    function (event, data) {
                list.find('[data-role=order]').each(function (i, el) {
                    $(el).val(i + 1);
                });
            },
            tolerance: 'pointer'
        });
    });
</script>
<style>
.accordion .config .admin__control-table {
    margin: 3rem 0 0.5rem;
}
</style>
