    <table class="admin__control-table" id="searchautocomplete-indices">
        <?php if (!empty($block->getData('options')) || empty($block->getData('field_id'))): ?>
            <?php foreach ($block->getOptionData($block->getData('options')) as $index): ?>
            <tr>
                <td class="col-order" data-role="draggable-handle">
                    <input type="hidden" data-role="order"
                           name="<?= /* @noEscape */ $block->getNamePrefix($index) ?>[order]"
                           value="<?= /* @noEscape */ $index['order'] ?>">
                </td>
                <td class="col-title"><?= /* @noEscape */ $index['title'] ?></td>
                 <td class="col-limit">
                   <select name="<?= /* @noEscape */ $block->getNamePrefix($index) ?>[limit]" 
                   class="admin__control-select">
                        <?php
                            $selectedLimit = $index['limit'] ?? ''; // Get selected value
                            $options = $block->getDropdownOptions(); // Fetch options from block
                        ?>
                        <?php foreach ($options as $value => $label): ?>
                            <option value="<?= /* @noEscape */ $value ?>" 
                            <?= /* @noEscape */ $selectedLimit == $value ? 'selected' : '' ?>>
                            <?= /* @noEscape */ $label ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="hidden" 
                    name="<?= /* @noEscape */ $block->getNamePrefix($index) ?>[type]" 
                    value='<?= /* @noEscape */ json_encode($index['type'] ?? "") ?>'/>
                    <input type="hidden" 
                    name="<?= /* @noEscape */ $block->getNamePrefix($index) ?>[identifier]" 
                    value='<?= /* @noEscape */ json_encode($index['identifier'] ?? "") ?>'/>
                    <input type="hidden" 
                    name="<?= /* @noEscape */ $block->getNamePrefix($index) ?>[title]" 
                    value='<?= /* @noEscape */ json_encode($index['title'] ?? "") ?>'/>

                </td>
                
            </tr>
        <?php endforeach ?>
    <?php else: ?>
        <td style="color: red;">Template variables not available</td>
    <?php endif ?>
    </table>
<script>
    require([
        'jquery',
        'collapsable'
    ], function ($) {
        var list = $('#searchautocomplete-indices');
        list.sortable({
            axis:      'y',
            handle:    '[data-role=draggable-handle]',
            items:     'tr',
            update:    function (event, data) {
                list.find('[data-role=order]').each(function (i, el) {
                    $(el).val(i + 1);
                });
            },
            tolerance: 'pointer'
        });
    });
</script>
<style>
.accordion .config .admin__control-table {
    margin: 3rem 0 0.5rem;
}
</style>